import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './global.css'
import React from 'react'
import { Provider } from '@/components/ui/provider'

const rubik = Rubik({
    subsets: ['latin'],
    variable: '--font-rubik',
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en" className={rubik.variable} suppressHydrationWarning>
            <body>
                <Provider>{children}</Provider>
            </body>
        </html>
    )
}
